"""otp added

Revision ID: 33ac59ce115c
Revises: 4b2cdd26b864
Create Date: 2026-02-09 15:10:48.411497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ac59ce115c'
down_revision = '4b2cdd26b864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
