"""added location

Revision ID: 838e399f8871
Revises: 33ac59ce115c
Create Date: 2026-02-13 11:24:13.315105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838e399f8871'
down_revision = '33ac59ce115c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    op.drop_table('user')
    op.drop_table('incident')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp')
        batch_op.drop_column('otp_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.create_table('incident',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('detected_class', sa.VARCHAR(length=100), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('reported_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=300), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('otp', sa.VARCHAR(length=10), nullable=True),
    sa.Column('otp_expiry', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
